In [4]:
import numpy as np  
arr1 = np.arange(10)  #1D Array Containing 0-9 numbers
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
arr2 = np.zeros((3,4))  #Zero Matrix of 3x4
print(arr2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
arr3 = np.eye(3,3)   #Identity Matrix of 3x3
print(arr3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
arr4 = np.linspace(0,1,5)   #Array containing 5 elements between 0-1
print(arr4)

[0.   0.25 0.5  0.75 1.  ]


In [9]:
for arr in [arr1,arr2,arr3,arr4]:
    print(arr.shape, arr.ndim, arr.dtype)

(10,) 1 int64
(3, 4) 2 float64
(3, 3) 2 float64
(5,) 1 float64


In [ ]:
matrix = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 10, 11, 12]
])

print(matrix[1,2])  #Element of 2nd row 3rd column
print(matrix[1])  #All the elments of 2nd row
print(matrix[:,2])  #All the elements of 3rd column
print(matrix[:2, 2:])  #Sub-matrix containg elements at 3rd & 4th column of  1st & 2nd row
print(matrix[0,::2])   #Elements of 1st row skipping 1 column

7
[5 6 7 8]
[ 3  7 11]
[[3 4]
 [7 8]]
[1 3]
