In [1]:
import numpy as np
X = np.array([
    [1500, 3, 5],
    [ 800, 2, 2],
    [2000, 5, 1],
    [1200, 4, 8]
])

#  NORMALISING

X_min = X.min(axis=0)
X_max = X.max(axis=0)
X_Norm = (X - X_min)/(X_max - X_min)

Y = np.ones((4,1))
X_Bias = np.hstack([Y,X_Norm])

print("Normalized:\n", X_Norm.round(2))
print("\nWith bias:\n", X_Bias.round(2))

Normalized:
 [[0.58 0.33 0.57]
 [0.   0.   0.14]
 [1.   1.   0.  ]
 [0.33 0.67 1.  ]]

With bias:
 [[1.   0.58 0.33 0.57]
 [1.   0.   0.   0.14]
 [1.   1.   1.   0.  ]
 [1.   0.33 0.67 1.  ]]


In [ ]:
# VECTORIZED Operations VS LOOPS

import time

data = np.random.randn(1_000_000)   # 1 million numbers

# Method 1: Python loop (slow)
start = time.time()
total = 0
for x in data:
    total += x ** 2
loop_time = time.time() - start

# Method 2: NumPy vectorised (fast)
start = time.time()
total_np =  np.sum(data**2)
numpy_time = time.time() - start

print(f"Loop:  {loop_time:.3f}s")
print(f"NumPy: {numpy_time:.3f}s")
print(f"NumPy is {loop_time/numpy_time:.0f}x faster")

#  One Line Codes for Mean, Standard Deviation, Minimum and Maximum of data
print(f"Mean: {np.mean(data)}")
print(f"Standard Deviation: {np.std(data)}")
print(f"Minimum: {np.min(data)}")
print(f"Maximum: {np.max(data)}")

Loop:  0.569s
NumPy: 0.009s
NumPy is 64x faster
Mean: -3.9352891220802376e-05
Standard Deviation: 1.0006560072759392
Minimum: -4.522061959950073
Maximum: 4.868721713911899
