In [1]:
import numpy as np
W = np.array([[2, 1, 0],
              [0, 3, 1],
              [1, 0, 2]], dtype=float)

x = np.array([15, 3, 5], dtype=float)

X = np.array([[15,3,5],[8,2,2],[20,5,1],[12,4,8]], dtype=float)

In [ ]:

# Task 1: single neuron prediction (dot product)

pred_single = np.dot(W[0],x)  #As 1x3 dot product with 3x1 gives 1x1 matrix
print(pred_single , pred_single.shape)

33.0 ()


In [ ]:
# Task 2: all 3 neurons for one sample

pred_all = np.dot(x,W) #As 1x3 . 3x3 gives 1x3
print(pred_all,pred_all.shape)

[35. 24. 13.] (3,)


In [ ]:
# Task 3: all 3 neurons for all 4 samples (batched)

pred_batch = X @ W.T
print(pred_batch,pred_batch.shape)

[[33. 14. 25.]
 [18.  8. 12.]
 [45. 16. 22.]
 [28. 20. 28.]] (4, 3)


In [ ]:
# Task 4: compute W transpose

W_T  = W.T
print(W_T,W_T.shape)

[[2. 0. 1.]
 [1. 3. 0.]
 [0. 1. 2.]] (3, 3)
