In [1]:
import numpy as np

ages    = np.array([22,17,35,14,28,45,16,31,19,42])
incomes = np.array([25,0,55,0,42,80,0,60,30,75])

In [2]:
adults = ages[ages>18]    # People of age greater than 18

adult_incomes = incomes[ages>18]

n_minors = ages[ages<18]  # Minors of age less than 18

mean_incomes = np.mean(incomes)

incomes_clean = incomes.copy()
incomes_clean[incomes_clean==0] = mean_incomes   # Replace all zeroes with mean incomes


print(adults, adult_incomes)
print("Minors:", n_minors)

[22 35 28 45 31 19 42] [25 55 42 80 60 30 75]
Minors: [17 14 16]


In [10]:
X = np.arange(20).reshape(10, 2)   # 10 samples, 2 features
y = np.array([0,1,0,1,1,0,1,0,1,0])

# Train/test split from scratch

np.random.seed(42)

indices = np.arange(len(X))
np.random.shuffle(indices)

split_at = int(0.8*len(X))   # Split at 80%

train_idx = indices[:split_at]

test_idx = indices[split_at:]

X_train, X_test = X[train_idx], X[test_idx]
y_train, y_test = y[train_idx], y[train_idx]

print(X_train, X_train.shape)
print(X_test, X_test.shape)



[[16 17]
 [ 2  3]
 [10 11]
 [ 0  1]
 [14 15]
 [ 4  5]
 [18 19]
 [ 8  9]] (8, 2)
[[ 6  7]
 [12 13]] (2, 2)
